### ISSUE TITLE
An executable named `arxiv-mcp-server` is not provided by package `arxiv-mcp-server`

### ISSUE THREAD

**Issue by Kevinello** [blazickjp/arxiv-mcp-server#35]
I'm using cherry studio to use this mcp server, with config in README:

![Image](https://github.com/user-attachments/assets/825b9a1f-f2ee-4015-9a81-2e92da9b7167)

then i face error log below:
```
[2025-06-10 01:12:31.864] [info]  [MCP] Starting server with command: /Users/kevinello/.cherrystudio/bin/uv tool run arxiv-mcp-server --storage-path /Users/kevinello/Downloads/paper
[2025-06-10 01:12:31.881] [info]  [MCP] Stdio stderr for server: arxiv-mcp-server  warning: An executable named `arxiv-mcp-server` is not provided by package `arxiv-mcp-server`.
```

notice that a new version of arxiv-mcp-server is published on [Jun 6, 2025](https://pypi.org/project/arxiv-mcp-server/0.2.11/), is there any changes not synced to README?

**Comment by inspirewind** [comment]
same issue

**Comment by Sai-Prathik** [comment]
I'm facing the same issue

**Comment by Appointat** [comment]
I have checked the original code. The readme is wrong, and config like this, which works on my PC:

```yml
    mcp_transport_config:
      transport_type: "STDIO"
      command: "uvx"
      args: ["--from", "arxiv-mcp-server", "arxiv-mcp-server", "--storage-path", "."]
```
